src/cryogen_core/compiler.clj
src/cryogen_core/io.clj
src/cryogen_core/sass.clj

This fixes an oversight from lacarmen/cryogen-core#4.
Also some slight refactoring of `get-resource`. FYI I concluded `.toURI` was redundant, let me know if there's a case I didn't consider.
This is completely separate from what I hope to do with checksum tracking (see #7).

Sass compilation respects :ignored-files config

---

project.clj
src/cryogen_core/watcher.clj

Also add pandect dependency.
It looks like switching to checksums for the watcher takes care of the double-compile problem I mentioned in #7 so no other fiddling should be necessary.

Use checksums instead of last modified times.

---

src/cryogen_core/io.clj

- this can/will happen if a user doesn't have a resource root directory,
e.g. if the resources/templates/asc/posts directory doesn't exist.
The add-asciidoc-support merge created a situation where users who haven't updated their projects to have all of the resources directories, e.g. resources/templates/asc/posts, could experience NullPointerExceptions.
This merge will fix that.

find-assets handles get-resource returning nil

---

src/cryogen_core/compiler.clj

As the filename extensions given by the render plugins are also used as
regex for replacing them with .html to generate URIs, the dot in front of
the extension was interpreted as an arbitrary character for the regex.
Also, it matched in the middle of a string. Now dots get quoted and a $
added to only match at the end of the filename.
Fix #16

Fix overly eager replacement of file extensions in uris

---

src/cryogen_core/compiler.clj
src/cryogen_core/sass.clj

This pull request adds the `--compass` argument to the command line that calls `sass` if the `compass` binary is available on the user's `$PATH`. 
While testing this change with a cryogen-generated blog and some non-trivial SASS files, it was necessary also to run the sass compiler in the `resources/templates` directory and to change the paths relative to that. The `sass --help` also mentions that when using `--update` (as we do here), we should be using `source-dir:destination-dir` form of arguments (which means no need to pass every sass file, so could be marginally faster). It's not unusual for sass directories to have one main `screen.scss` file and lots of included utils with names starting with `_` which don't themselves generate any css - letting the sass compiler worry about all …

Compile sass with compass when available

---

src/cryogen_core/rss.clj

1) Removed the "author" tag from each "item".  The presence of this tag is ok here but the xsd requires that the content include a valid email address, not just the name string coming from the site config (Forms that pass validation are "test@xyz.com" or "test@xyz.com (Test McTester)" ).  And who would want to advertise their real email like that?  :)
2) Removed the "author" tag from the "channel".  "author" isn't a valid child element of a channel.  There is a child element called "webMaster" that is a close analogue but it also requires content as above.
Another approach would be to use the "webMaster" tag on the "channel" and document/change the contents of the :author key in config.edn to contain "test@xyz.com (Test McTester)".

Modification to allow the generated rss xml to pass xsd validation.

---

src/cryogen_core/compiler.clj

Following the discussion from [cryogen/#73](https://github.com/cryogen-project/cryogen/issues/73), this change allows posts to override the date from the filename by setting `:date` in the post metadata.
I think this change starts to open up the possibility of having different naming conventions for posts and ultimately support a more flexible and user-defined URL structure.
The `:date` must be in the same format as defined in `config.edn`. I investigated adding support for `#inst` date types but then thought that maybe it should be kept in the same format for now so it is easy for a person to read and edit.

Optional :date key can be provided in metadata

---

src/cryogen_core/compiler.clj

Pull request for: cryogen-project/cryogen-core#35
For certain pages a key with a boolean value is added to the config map which can then be used in templates to determine if it is the page being rendered. Not all pages have this key and boolean value. Instead of adding additional keys for every page a new generic key, 'active-page', has been added and its value is the page name, ex: 'home', 'archives', 'tags', etc. The default value is 'home'. This key can then be used in any template to check the page which is currently being rendered.

Add active-page key to config map

---

src/cryogen_core/compiler.clj
src/cryogen_core/rss.clj

Add an enclosure tag to a post's metadata to let a podcast client
to deliver your audio content.  It should look like this:
`:enclosure [{:url "<full-url>"}]`
Without the brackets, you end up with `NullPointerExceptions`, so
make sure you have that.
The URL should be the full location of where the audio file is
hosted (not relative), so for example:
`:enclosure [{:url "http://www.example.com/01_episode_IV.mp3"}]`
I created a bunch of markdown files with just the enclosure and
info about the audiobook with the following bash snippet:
```bash
find -L books -type f -iname "*mp3" | sort | while read mp3; do name=$(basename $mp3 .mp3); book=$(basename "$(dirname $mp3)"); echo "{:title \"$name\"\n:layout :post\n:tags [\"audiobooks\" \"$book\"]\n:enclosure [{:url …
```

Add enclosure tag to facilitate Podcasting with Cryogen

---

src/cryogen_core/compiler.clj

This commit replaces a regular expression lookup with a simple
String/indexOf substring search.
It addresses pathological cases in which re-find took several
seconds to process contents of a blog post. An example of such
a case was a post with 16kB of nested HTML tags in a single line.

create-preview: simplify the more marker lookup

---

src/cryogen_core/watcher.clj

This makes compilation of cryogen-core.watcher faster by reducing the
number of its dependencies. Now it depends just on pandect.algo.md5
instead of all pandect.algo.*

require pandect.algo.md5 instead of pandect.core

---

src/cryogen_core/compiler.clj

This makes each markup implementation process posts in parallel.
In case of a simple test blog with 4 markdown pages mean compilation
time was reduced from 395 to 330ms. In the experiment I used OpenJDK 8
running `lein ring server` on a 4 core CPU.

Parallelize read-posts with pmap

---

src/cryogen_core/toc.clj
test/cryogen_core/toc_test.clj

@lacarmen This should deliver the promised functionality for nested lists which behave reasonably, no matter what the order of the headers are. It also flattens the lists so that having an h1 at the end of a list of h2's doesn't indent the list of h1's.
I also added a regression testing suite covering the expected behavior for this style of building lists. This way there is a basis for which behavior is proper.
This set of commits, and the associated tests, should help resolve these issues:
*  #19

Use Zippers to Build TOC Data Structure

---

src/cryogen_core/compiler.clj
test/cryogen_core/compiler_test.clj

Using Cryogen with {:previews? true}, the preview page (index.html) corrapsed when post contains more marker.
`content-with-more-marker` returns a HTML string when the `content` conteins more marker ("").
HTML tags in the parameter `content` is balanced.
ex.
````HTML
<div id='post'>
<div class='post-content'>
this post has more marker
and more content.
</div>
</div>
````
But original code, `content-with-more-marker` function breaks the balance.
result of original code:
````HTML
<div id='post'>
<div class='post-content'>
this post has more marker
````
Afer this patch applied, `tagsoup` read above text and `hiccup` re-render to HTML text with correct balanced tags.
````HTML
<div id='post'><div class='post-content'>
this post has more marker
</div></div>
````

content-with-more-marker returns with correct html closing tags

---

src/cryogen_core/compiler.clj

This param is available on the index page params by default when previews are disabled, but if previews are enabled then its nil.  It should be available regardless of the setting.
BTW, thanks for making cryogen, it's really nice!

Add home to index params when previews are enabled

---

src/cryogen_core/rss.clj

I'm able to add to the post metadata information about the author and a short description of the post, and then use this information in the HTML template (following this [simple approach](https://github.com/cryogen-project/cryogen/issues/30))
Now, I'd also like to have this information in the RSS and this PR is about adding those two values. The author is simply the author, while the description can be either the description specified in the post metadata or the content of the post. This also fit the [specification](http://cyber.law.harvard.edu/rss/rss.html#hrelementsOfLtitemgt): "_...if so its description is a synopsis of the story, and the link points to the full story. An item may also be complete in itself, if so, the description contains the text (entity-encoded HTML is allowed), …

Add author and (short) description for RSS

---

src/cryogen_core/compiler.clj

For each author, I'd like to generate a page with all his/her posts.
To keep backwards compatibility this would be enabled only if the `author-root-uri` key is not `nil` (in the `config.edn` file). It would work just like `page-root-uri` or `post-root-uri`.

Add multiple authors filtering support

---

src/cryogen_core/compiler.clj
src/cryogen_core/io.clj

cryogen-project/cryogen#89
When `clean-urls?` is set in config, emit pages as subdirectories
```
prefix/root/page-name/index.html
```
instead of
```
prefix/root/page-name.html
```
Links in emitted HTML then point to `prefix/root/page-name/`. When `clean-urls?` not set, behaves as
before.
Refactor most URI generation into a new `compiler/page-uri` function. `compiler/page-uri` replaces most calls<sup>†</sup> to `io/path`, all calls to `compiler/post-uri` and all calls to the old `compiler/page-uri`.
Introduce function `compiler/write-html`. When `clean-urls?` is set, spits emitted HTML into subdirectories as described above; otherwise behaves like `io/create-file`. Replaces most<sup>†</sup> calls to `io/create-file`.
Introduce function `io/create-file-recursive`. Creates file parent when …

Implement clean URLs feature (Issue #89 in cryogen-project/cryogen)

---

src/cryogen_core/compiler.clj

The blog that I'm moving to cryogen currently groups the posts by year instead of by year/month. This change makes the grouping configurable while defaulting to the current behavior of year/month grouping on posts.

Make archive grouping configurable

---

project.clj
src/cryogen_core/watcher.clj

This is a follow-up to PR #46. It replaces the 300ms loop with a file
watcher. Hawk is a wrapper around java.nio.file.WatchService coming with
proper OS X support.
Now rebuilds should be instantaneous.

Use Hawk in cryogen-core.watcher

---

src/cryogen_core/compiler.clj
test/cryogen_core/compiler_test.clj

By default, when using markdown files, Cryogen will look for
`resources/templates/md/pages/*.md`. This commits allows Cryogen to fall back to
`resources/templates/pages/*.md` in the case that it can't find any files in the
former directory. It works similarly for posts and Asciidoc files.
Since we're looking specifically for `*.md` for Markdown files and `*.asc` for
Ascii files, this is an opportunity to eliminate redundancy.

Fallback to resources/templates/{pages,posts}

---

src/cryogen_core/compiler.clj
src/cryogen_core/markup.clj
test/cryogen_core/compiler_test.clj

This is a second attempt at #67. I addressed a missing `dir` call in copying the resource directory. In addition to tests, I also tested the feature in a test blog project.

Another attempt at fallback to resources/templates/{pages,posts}

---

src/cryogen_core/compiler.clj

This commit generates files as follows
```
templates/md/pages/dir/test.md -> public/dir/test/index.html
```
while the current version
```
templates/md/pages/dir/test.md -> public/test/index.html
```

support sub directories in pages and posts

---

src/cryogen_core/sass.clj

catch the (previously uncaught) exception when there isn't a `compass`
binary on the `$PATH`, return `false` instead

bugfix for compass-installed?

---

.gitignore
project.clj
src/cryogen_core/compiler.clj
src/cryogen_core/sass.clj

The path is converted to forward slash before further processed
The executables for sass and compass are configurable, that's because
on a Windows installation they are named sass.bat and compass.bat
The default is still the Unix version.

Provided fixes make cryogen work on Windows.

---

src/cryogen_core/compiler.clj

This allows users to set a :hide-future-posts? key in their config file to include only current and past blogs in the compiled site. This allows for easy drafting of future articles, and can be used to automatically publish new articles to the static site (provided you recompile of course).
Feel free to change the key name as you wish.
Hope you'll find this useful!

conditionally drop any posts with dates set in the future

---

.gitignore
project.clj
src/cryogen_core/compiler.clj

Hi,
I added a enhanced homepage handling. You're now able to fund homepage on a page instead of newest post. 
In order to do so, you can add a page containing following meta:
```
{:title "some title"   ;not relevant to feature
:layout :home        ;other layout may be chosen
:page-index 0        ;if there are more than one defined homepages
:home? true          ;relevant meta
}
```
Layout will be respected. 
If you have more than one homepage, the first is chosen. 
Homepages will not be rendered as normal page. 
As I can see, I preserved backward compatibility.
In addition I added a :debug? switch to configuration - so a more verbose output can be triggered.

enhanced homepage handling & debug option

---

project.clj
src/cryogen_core/compiler.clj
test/cryogen_core/compiler_test.clj

Tagsoup depends on an ancient version of clojure.data.xml that doesn't compile with clojure 1.9.0-alpha12. I changed to enlive, which seems a lot better maintained in general.

Depend on enlive instead of tagsoup (to be able to upgrade to clojure 1.9.0)

---

project.clj
src/cryogen_core/toc.clj
test/cryogen_core/toc_test.clj

Almost the same thing; it doesn't insert missing html, head and body
tags, but in this case we only care about the stuff in the body.

Remove crouton dep because enlive does the same thing

---

project.clj
src/cryogen_core/compiler.clj
test/cryogen_core/compiler_test.clj

Added some tests and testing, but it could definitely use a little more.
The code has some inconsistencies between using nil values and missing keys in options maps. The schema could be made clearer if this was standardized.
https://github.com/cryogen-project/cryogen-core/issues/88

Config validation

---

src/cryogen_core/compiler.clj
src/cryogen_core/io.clj
src/cryogen_core/sass.clj

This also fixed a few inconsistencies in how the `css` directory is handled.
NB: the `:sass-dest` key is no longer used. The code separates Sass compilation from copying files into `public/` so all Sass files are not compiled into their directory.
Fixes #90.
An accompanying change to the Leiningen template repo will ensure there's a `css` directory by default.
There's also some minor text changes, and a little more output about copying resources. I guessed you wouldn't mind those, but let me know if you want to keep the PR simpler.

Enable Sass in themes

---

src/cryogen_core/compiler.clj

Allow the overriding of config values by passing an optional argument to compile-assets-timed. Useful for environment specific configuration. (e.g. separate prod and dev reCaptcha public keys, or local vs production API endpoint urls)

Add ability to optionally override config.edn

---

src/cryogen_core/rss.clj

I started using Cyrogen for my blog and it is working very well for me. I appreciate that you made it.
I noticed an issue recently where the feed xml file can be invalid because of a blank <enclosure>. To see this behavior try the following.
Prior to the change this is the report I was receiving: 
```
This feed does not validate.
line 42, column 0: Missing enclosure attribute: length (14 occurrences) [help]
<enclosure>
```
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fblog.bradlucas.com%2Fclojure0.xml
Using my post fix version here I get the following:
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fblog.bradlucas.com%2Fclojure.xml
Let me know what you think. 
Thanks
- Brad

only add enclosure to map if not nil

---

src/cryogen_core/markup.clj

AsciiDoc has a syntax to embed Youtube video like [this](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#videos).
This will compiled to an iframe with source to `//www.youtube.com/embed...`
Current regex will break the link by adding blog-prefix to it, changing it to `/blog//www.youtube.com/embed...`
I changed the regex to exclude links that start with double slash.

Fix blog-prefix added to protocol-relative url

---

src/cryogen_core/compiler.clj
src/cryogen_core/io.clj
test/cryogen_core/compiler_test.clj

Added ability for themes to have their own config.edn and specify additional resource and Sass directories.
NB: may want to consider how the merging of theme config works in the long run. It uses `merge-with into` to combine collections, but this will break if someone adds a theme config option that's a scalar. When `overrides` uses `deep-merge`, any key that's not a map is completely replaced by the override; we want to merge things like `:sass-src` and `:resources` though, not replace them.
Let me know if you want this a bit more future-proof.

Added theme config ability

---

project.clj

Hi and thanks for Cryogen!
This PR is specifically to include a fix for `clj-rss` that removes extra newlines which I'd like to see included: https://github.com/yogthos/clj-rss/pull/16 (I know the build failed on the PR but that's because the travis config was updatd on master rather on this branch).
I'm also updating `selmer` because seems to make sense to do it at the same time, but happy to leave that out if you prefer.

Updated depedencies, including fix for rss feeds newlines

---

src/cryogen_core/compiler.clj
src/cryogen_core/schemas.clj
test/cryogen_core/compiler_test.clj

Full disclosure; I haven't tested this yet. I'll get around to testing it in the next day or so.
This work represents most of the solution I outlined here: https://github.com/cryogen-project/cryogen/issues/166#issuecomment-493294999
Once this branch is confirmed completed and ready to be merged, there are still `clean-urls?` references in [cryogen-project/cryogen](https://github.com/cryogen-project/cryogen) that also need to be addressed as well as documentation updates that will be necessary.

Clean URLs with and without trailing slash

---

src/cryogen_core/compiler.clj
src/cryogen_core/schemas.clj

Fix cryogen-project/cryogen#193 and default page layout to `:page`, post layout to `:post`.

Fix #193 - default layout values

---

src/cryogen_core/compiler.clj

so that they can use it in `<meta name=description ..>` and for previews on Fb/Slack/.. e.g.
via `<meta property=og:description ...>`.
The new post/page `:description` is derived from the HTML previews, by default including text from  `p` and `hN` tags.
You want to use it as `{{post.description}}` in a template.
When this is merged, we should update templates as follows:
```html
...
<title>{{title}}{% block subtitle %}{% endblock %}</title>
{% block meta %}
<meta name="description" content="{{description}}">
<meta name="keywords" content="">
{% endblock %}
...
{% extends "/html/base.html" %}
{%block subtitle %}: {{post.title}}{% endblock %}
{% block meta %}
<meta name="keywords" content="{% for tag in tags %}{{tag.name}}{% if not forloop.last %},{% endif %}{% endfor %}">
{% if …
```

Expose plaintext `description` to pages/posts

---

src/cryogen_core/compiler.clj

so that they can f.ex. display a list of tags with their counts.
**NOTE: This is not a finished solution** - it is intended as a base for discussion before I commit too much time [possibly going in the wrong direction] to it. So what do you think, @lacarmen ? 
Instead of adding `:extend-params-fn` to the overrides, we could pass it
as an extra param but it is complicated because we need to do it on 2
functions and would then perhaps need to support 3 arities. This seems
simpler.
* Rename `overrides` to something better (what???)
* Use Spec to document the arguments to the extend-params-fn?
* Document extend-params-fn in docstrings and perhaps the site docs?

WIP Enable users to derive extra params from params + site data

---

src/cryogen_core/compiler.clj

Allow users to supply a function run on every parsed page/post to
update it.
Example uses:
- support for a custom `:slug` metadata in a post to override the defaul
uri
- post-process the HTML to add self-links to every heading
I struggled to find a good name for "post or page". In the end I have fallen back on the HTML standard and adopted the name it uses for the "main content", i.e. "article". Any better ideas?
Notice that while `extend-params-fn` runs very late in the process, this runs very early so it can modify the base data used to create the various site data such as posts and posts-by-tags, while `extend-params-fn` would need to modify all the places where e..g a particular post is used.

Add :update-article-fn to customize parsed page/..

---

src/cryogen_core/compiler.clj
src/cryogen_core/klipse.clj
src/cryogen_core/rss.clj
src/cryogen_core/toc.clj
src/cryogen_core/util.clj
src/cryogen_core/zip_util.clj
test/cryogen_core/compiler_test.clj
test/cryogen_core/klipse_test.clj
test/cryogen_core/toc_test.clj
test/cryogen_core/util_test.clj
test/cryogen_core/zip_util_test.clj

passing around the Enlive DOM tree instead of the final HTML text
so that it is easier to work with both for us and users, instead of
repeatedly transforming text<>dom.

Fix #131 Replace :content with :content-dom

---

src/cryogen_core/compiler.clj

Resolves #135 
Introduces a new `:type` key to post/page maps
Slight problem: neither `read-page-meta` function nor `MetaData` spec distinguishes between pages and posts. I have not therefore updated the spec with a `:type` key.
What's the intended direction here - do y'all want a stricter distinction between pages/posts, or are they meant to stay ambiguous?

Fix: a page will correctly render its content when set as homepage 

---

src/cryogen_core/compiler.clj

This should fix the scenario described in the #109

fix #109: parse post dates when posts are stored in subdirectories

---

project.clj
src/cryogen_core/compiler.clj

Upgrade outdated dependencies as per the GH [Dependencies Status](https://versions.deps.co/cryogen-project/cryogen-core) report: [![Dependencies Status](https://versions.deps.co/cryogen-project/cryogen-core/status.svg)](https://versions.deps.co/cryogen-project/cryogen-core)
NOTE: I have now tested it on my blog. It was OK, I only had to fix the Selmer config.

Upgrade outdated dependencies

---

src/cryogen_core/compiler.clj
src/cryogen_core/io.clj
src/cryogen_core/markup.clj
src/cryogen_core/sitemap.clj
test/cryogen_core/compiler_test.clj

Here are a set of PRs that implement multiple filename extensions in Markup.
Prompted by Issue  Number 6 in the `cryogen-asciidoc` repo.
Related PRs are
- `cryogen-asciidoc` PR number 7
- `cryogen-docs` PR number 32
- `cryogen-markdown` PR number 13
- `cryogen-flexmark` PR number 6

Allow multiple extensions in Markup.

---

src/cryogen_core/compiler.clj

so that e.g. asciidoctor can read additional attributes from the page
See https://github.com/asciidoctor/asciidoctor/issues/252

Include :page-meta in config passed to markdown render

---

src/cryogen_core/compiler.clj
test/cryogen_core/compiler_test.clj

Tags which contain special characters like a # or ? produce a link which doesn't reach the tag output page. Fix: URL encode the tag in the links

Fix 142: URL encode tag links

---

src/cryogen_core/compiler.clj
src/cryogen_core/io.clj
src/cryogen_core/sitemap.clj

The compiler now passes the whole `config` map into `sitemap/generate` and that destructures `ignored-files` and a new optional key `ignored-paths` and filters the latter out of the result of the `find-assets` call.
The `ignore-path` function mirrors the `ignore-name` function in `cryogen-core.io` -- should it perhaps be in that ns in case other code might want to reuse it later?
Is the new config key `:ignore-paths` a good choice? Should it be something sitemap-specific (since only `sitemap/generate` uses it)?

Allow certain paths to be excluded from the sitemap

---

project.clj
src/cryogen_core/compiler.clj

... right before the article is written to the disk.
Add `:postprocess-article-html-fn` config option that will be called on the article
(page/post) after it is transformed from markup to HTML.
This can be used e.g. to run it through Selmer so that you can use Selmer templating
in your markup and get it processed - see #139 for the original request for that.

Enable postprocessing of article HTML

---

CHANGELOG.md
CONTRIBUTING.md
RELEASE.md

This is my first cut at adding community support files.  In particular, I've added
* `CONTRIBUTING.md` about how to make contributions to this repo.
* `CHANGELOG.md` to document changes. 
* `RELEASE.md` to document how to make releases.
I've tried to retrieve the changes made in the past and incorporate them into the `CHANGELOG.md`, but they may be incomplete.
My understanding of Github releases is rudimentary, so please verify that what I have said is correct.
Any comments or suggestions for improvement are welcome.
I have not yet added a PR template, but wanted to get these published first, so that we can get some experiences with the release process.

Add support files

---

CONTRIBUTING.md
RELEASE.md

* Do not mandate but do recommend creating a fork
* Leave out details that most GH users know so that the important
information is more visible.

Simplify the contrib/release docs

---

CHANGELOG.md
README.md
project.clj

- The CHANGELOG links for the diffs between version was broken. Fixed.
- Added Highlights for 0.4.0 in CHANGELOG.
- Updated Copyright notice in README.
- Updated deps to latest.

Prepare for release 0.4.0

---

src/cryogen_core/compiler.clj

because 1) it would break rendering of posts and pages due to the order
of the cond clauses in `htmlize-content`
2) even if we changed the order so that posts is last (which seems to
work fine) it would still not work as expected because some pages
define :posts themselves, overriding this - e.g. tag pages.
The best solution is thus tell the user not to do this and use another key instead.
Fixes #156

Fail if extend-params-fn adds :posts

---

src/cryogen_core/compiler.clj
test/cryogen_core/compiler_test.clj

The URI for each author page was not URL-encoded.
Now it is.

URL encode the author URI.
